import ContactPage from "@/components/Home/ContactPage";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Design Role | Contact",
    description: "Generated by Design Role",
};

const Contact = () => {

    return (
        <div>
            <ContactPage />
        </div>
    );
};

export default Contact;
