import ProjectHome from "@/components/dashboardPage/ProjectHome";
import { Metadata } from "next";


export const metadata: Metadata = {
    title: "Design Role | Dashboard | Projects",
    description: "Generated by Design Role",
};

const DashboardProjects = () => {


    return (
        <div>
            <ProjectHome />
        </div>
    );
};

export default DashboardProjects;
