import BlogAllHome from "@/components/Home/BlogAllHome";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Design Role | Blogs",
    description: "Generated by Design Role",
};

const BlogPage = () => {

    return (
        <div>
            <BlogAllHome />
        </div>
    );
};

export default BlogPage;
