import Projects from "@/components/Home/Projects";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Design Role | Projects",
    description: "Generated by Design Role",
};

const ProjectsPage = () => {

    return (
        <div>
            {/* My project */}
            <div>
                <Projects />
            </div>
        </div>
    );
};

export default ProjectsPage;
