import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Design Role | Dashboard",
    description: "Generated by Design Role",
};

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <div className="min-h-screen">
                {children}
            </div>
        </div>
    );
}