
import Footer from "@/components/shared/Footer";
import Navbar from "@/components/shared/Navber";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Design Role | Home",
    description: "Generated by create design role",
};

export default function HomeLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <div>
                <Navbar />
            </div>
            <div className="min-h-screen">
                {children}
            </div>
            <Footer />
        </div>
    );
}